In [3]:
import pandas as pd
import numpy as np

In [5]:
path = r'C:\Users\88696\Desktop/'
df = pd.read_csv(f'{path}account_result.csv',encoding='utf-8-sig',low_memory=False)
df

,id,processedNotes,real_name,clientNameIpt,clientNameEn,clientNameNtv,applyType,balance,equity,p_id,...,markUserType,reasonShow,dapCpa,dapCpaOwner,dapCpaSale,prohibitAuditing,mt4Group,dataSource,queryUserId,error
0,6717958.0,NaN,Ikhtiyor Azamov,Ikhtiyor Azamov,IXTIYOR BAXTIYOR O'G'LI A'ZAMOV,IXTIYOR BAXTIYOR O'G'LI A'ZAMOV,NaN,0.00,0.00,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_UK3', 'category': 'MT5', 'value'...",10504118,NaN
1,5648918.0,NaN,Sourav Mandal,Sourav Mandal,Sourav Mandal,Sourav Mandal,NaN,40.82,40.82,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_UK2', 'category': 'MT5', 'value'...",9512162,NaN
2,6268409.0,NaN,Tridev sharma,Tridev sharma,TRIDEV SHARMA,TRIDEV SHARMA,NaN,0.00,0.00,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_AU4', 'category': 'MT5', 'value'...",10096195,NaN
3,6707346.0,NaN,Aishwarya Biradar,Aishwarya Biradar,AISHWARYA AISHWARYA,AISHWARYA AISHWARYA,NaN,97000.00,97000.00,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_AU11', 'category': 'MT5', 'value...",10494298,NaN
4,6695957.0,NaN,Dattatray Bhagwan Madake,Dattatray Bhagwan Madake,DATTATRAY BHAGWAN MADAKE,DATTATRAY BHAGWAN MADAKE,NaN,121.54,121.54,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_AU10', 'category': 'MT5', 'value...",10243360,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13959,4415734.0,NaN,紹羽劉,紹羽劉,NaN,NaN,NaN,0.35,1.35,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_AU6', 'category': 'MT5', 'value'...",3774278,NaN
13960,4304206.0,NaN,紹羽劉,紹羽劉,NaN,NaN,NaN,1061269.86,1053873.11,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_AU6', 'category': 'MT5', 'value'...",3774278,NaN
13961,4304193.0,NaN,紹羽劉,紹羽劉,NaN,NaN,NaN,0.00,730.71,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_AU6', 'category': 'MT5', 'value'...",3774278,NaN
13962,4304179.0,NaN,紹羽劉,紹羽劉,NaN,NaN,NaN,71647.09,71371.47,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_AU6', 'category': 'MT5', 'value'...",3774278,NaN
13963,4304175.0,NaN,紹羽劉,紹羽劉,NaN,NaN,NaN,39.06,7.98,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"{'name': 'MT5_AU6', 'category': 'MT5', 'value'...",3774278,NaN

In [59]:
df.columns[40:80]

Index(['applyName', 'applyAccount', 'accountDealType', 'mt4_datasource_id',
       'agent_mt4Account', 'leverage', 'server', 'currency', 'accountMT4Type',
       'accountMT4Type_display', 'mt4GroupId', 'ownerId', 'owner', 'email_sub',
       'phone_num', 'cpa', 'opNote', 'cpaSales', 'affid', 'ownerAlias',
       'isArchive', 'isHidden', 'user_type', 'isregist', 'ownerIbLevel',
       'ibGroup', 'userRiskRank', 'saleslogcount', 'is_riskRank', 'p_ids',
       'org_name', 'commission_code_id', 'applicantServer', 'userName',
       'allVolume', 'allCommission', 'pammCommission', 'account', 'variety',
       'closeTime'],
      dtype='object')

In [65]:
columns = ['user_id','mt4_account','accountMT4Type_display', 'currency','group','isHidden','profit', 'margin']
df1 = df[columns]
df1

,user_id,mt4_account,accountMT4Type_display,currency,group,isHidden,profit,margin
0,10504118.0,27687628.0,MT5 SF Standard STP,USD,VU_Hedge\M_VU_NM_USD,NaN,0.00,0.0
1,9512162.0,23153323.0,Hedge STP,USD,VU_Hedge\M_VUT_USD,NaN,0.00,0.0
2,10096195.0,26635003.0,Hedge STP,USD,VU_Hedge\M_VUT_USD,NaN,0.00,0.0
3,10494298.0,27488988.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0
4,10243360.0,27717845.0,MT5 Swap free STP,USD,VU_Hedge\M_VUT_NM_USD,NaN,0.00,0.0
...,...,...,...,...,...,...,...,...
13959,3774278.0,18415746.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0
13960,3774278.0,18411560.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-12340.00,0.0
13961,3774278.0,18411559.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0
13962,3774278.0,18411555.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-1107.62,0.0
13963,3774278.0,18411554.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-31.85,0.0

In [75]:
# 過濾"Social Trading"關鍵字
df2 = df1[~df1['group'].str.contains(r'Social_Trading',na=False)] 

# 撰寫Boolean Logic
df2

,user_id,mt4_account,accountMT4Type_display,currency,group,isHidden,profit,margin
0,10504118.0,27687628.0,MT5 SF Standard STP,USD,VU_Hedge\M_VU_NM_USD,NaN,0.00,0.0
1,9512162.0,23153323.0,Hedge STP,USD,VU_Hedge\M_VUT_USD,NaN,0.00,0.0
2,10096195.0,26635003.0,Hedge STP,USD,VU_Hedge\M_VUT_USD,NaN,0.00,0.0
3,10494298.0,27488988.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0
4,10243360.0,27717845.0,MT5 Swap free STP,USD,VU_Hedge\M_VUT_NM_USD,NaN,0.00,0.0
...,...,...,...,...,...,...,...,...
13959,3774278.0,18415746.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0
13960,3774278.0,18411560.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-12340.00,0.0
13961,3774278.0,18411559.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0
13962,3774278.0,18411555.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-1107.62,0.0
13963,3774278.0,18411554.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-31.85,0.0

In [135]:
row = df2.iloc[10]
account_type      = row["accountMT4Type_display"]
currency_type     = row["currency"]
group_type        = row["group"]

has_currency = currency_type in group_type
has_p  = 'P' in group_type
has_nm = 'NM' in group_type
has_ns = 'NS' in group_type

if "Swap free ECN" in account_type:
    print('Swap free ECN boolean test: ',has_currency and has_p and has_nm)
elif "ECN" in account_type:
    print('ECN boolean test: ',has_currency and has_p)
elif "Swap free STP" in account_type:
    print('Swap free STP boolean test: ',has_currency and not has_p and has_nm)
elif "STP" in account_type:
    print('STP boolean test: ',has_currency and not has_p)

ECN boolean test:  True

In [211]:
import re
def parse_group(group):
    tokens = re.split(r'[_\\]', str(group))  # 同時切 _ 和 \
    return set(filter(None, tokens))        # 去掉空字串

def group_checking(row):
    account_type  = str(row["accountMT4Type_display"])
    currency_type = str(row["currency"])
    group_tokens  = str(row["group"])#parse_group(row["group"])

    has_currency = currency_type in group_tokens
    has_p  = "P"  in group_tokens
    has_nm = "NM" in group_tokens
    has_ns = "NS" in group_tokens
    has_bc = "BC" in group_tokens
    has_r  = "R"  in group_tokens
    has_tv = "TV" in group_tokens
    
    if "Swap free ECN" in account_type:
        return has_currency and has_p and has_nm
    elif "ECN" in account_type:
        return has_currency and has_p

    elif "Swap free STP" in account_type:
        return has_currency and not has_p and has_nm
    elif "STP" in account_type:
        return has_currency and not has_p

    elif "SF Perpetual" in account_type:
        return has_currency and has_bc and has_nm
    elif "Perpetual" in account_type:
        return has_currency and has_bc
        
    elif "SF Premium" in account_type:
        return has_currency and has_r and has_nm
    elif "Premium" in account_type:
        return has_currency and has_r 
        
    elif "Trading View" in account_type:
        return has_currency and has_tv
    
    return False

In [213]:
df2["Group Checking"] = df2.apply(group_checking, axis=1)
df2

C:\Users\88696\AppData\Local\Temp\ipykernel_38520\2495516769.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Group Checking"] = df2.apply(group_checking, axis=1)

,user_id,mt4_account,accountMT4Type_display,currency,group,isHidden,profit,margin,Group Checking
0,10504118.0,27687628.0,MT5 SF Standard STP,USD,VU_Hedge\M_VU_NM_USD,NaN,0.00,0.0,True
1,9512162.0,23153323.0,Hedge STP,USD,VU_Hedge\M_VUT_USD,NaN,0.00,0.0,True
2,10096195.0,26635003.0,Hedge STP,USD,VU_Hedge\M_VUT_USD,NaN,0.00,0.0,True
3,10494298.0,27488988.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0,True
4,10243360.0,27717845.0,MT5 Swap free STP,USD,VU_Hedge\M_VUT_NM_USD,NaN,0.00,0.0,True
...,...,...,...,...,...,...,...,...,...
13959,3774278.0,18415746.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0,True
13960,3774278.0,18411560.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-12340.00,0.0,True
13961,3774278.0,18411559.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,0.00,0.0,True
13962,3774278.0,18411555.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-1107.62,0.0,True
13963,3774278.0,18411554.0,MT5 Standard STP Cent,USC,VU_Hedge\M_VUT_USC,NaN,-31.85,0.0,True

In [215]:
df3 = df2[df2['Group Checking'] == False]
df3['accountMT4Type_display'].unique()

array(['PAMM Investor', 'MT5 PAMM Investor', 'MT5 Swap free STP', nan,
       'MT5 Swap free ECN', 'Hedge STP', 'MT5 Swap free ECN Cent',
       'MT5 Swap free STP Cent', 'Standard STP'], dtype=object)

In [217]:
df3[df3['accountMT4Type_display'].str.contains(r'Premium',na=False)]

Empty DataFrame
Columns: [user_id, mt4_account, accountMT4Type_display, currency, group, isHidden, profit, margin, Group Checking]
Index: []